# TODO:

1) Add standart deviation implementation

2) Add comments

3) Maybe we need to redefine createMatrix for distributive cultures

4) Maybe turn Votings in different classes

5) Table1 all values"


# In silico Voting Experiments

Implementation of cultures and voting rules

Code uploaded to the github.

In [1]:
import pandas as pd
import sklearn
import math
import numpy as np
import random
random.seed(12)

# 2 Cultures

In [2]:
class Сulture:
    def __init__(self, n, K):
        self.n = n
        self.K = K
        
        # self.P - matrix with profiles
        self.P = np.zeros((self.n, self.K))
        
        # self.M - matrix with borda scores
        self.M = np.zeros((self.K, self.K))
        
        self.ctype = None
        self.cctype = None
    
#     def createMatrices(self):
#         # matrix K x K 
        
#         self.P = self.createProfiles()
#         if(self.ctype == 'Rousseauist_culture' or self.ctype == 'Impartial_culture'):
#             self.M = self.createBordaMatrix()
        
#         elif(self.ctype == 'Distributive_culture'):
#             self.M = self.createBordaMatrix()
        
#         elif(self.ctype == 'Spatial_culture'):
#             pass
        
#         return self.P, self.M
    
#     # For sincere voting
#     def createBordaMatrix(self):
#         tempM = np.zeros((self.K, self.K))
#         for p in range(self.n):
#             for k1 in range(self.K):        
#                 for k2 in range(k1+1, self.K):
#                     if( self.P[p,k1,k2] == 1):
#                         tempM[k1, k2] += 1
#                     elif(self.P[p,k2,k1] == 1):
#                         tempM[k2, k1] += 1
#         for k in range(self.K):
#             tempM[k,k] = self.n/2
#         return tempM
    
#     def linearIntoMatrix(self, profile):
#         tempM = np.zeros((self.K, self.K))
#         for i in range(self.K):
#             for j in range(i+1, self.K):
#                 tempM[profile[i], profile[j]] += 1
#         return tempM

# 2.1 Rousseauist cultures

In [3]:
class Rousseauist_culture(Сulture):
    # We assume that 1 > 2 > ... > K
    def setParams(self, alpha, beta):
        # alpha >= 0
        # beta >= 0
        self.alpha = alpha
        self.beta = beta
        self.ctype = "Rousseauist_culture"
    
    def createProfiles(self):
        tempP = np.zeros((self.n, self.K, self.K))
        for p in range(self.n):
            for k1 in range(self.K):
                for k2 in range(k1+1, self.K):
                    if( random.random() < self.getP(k1,k2)):
                        tempP[p, k1, k2] = 1
                    else:
                        tempP[p, k2,k1] = 1 
        self.P = tempP
        return tempP
        
    def getP(self, k1, k2):
        # Truchon and Drissi-Bakhkhat
        # k > k'
        if(k2 <= k1): 
            raise NameError("k >= k'")
            
        s = math.exp(self.alpha + self.beta*(k2-k1-1))
        return s/(1+s)

In [4]:
r = Rousseauist_culture(3,3)
r.setParams(1,1)
P = r.createProfiles()
print(f'P: \n {P}')
# print(f'M: \n {M}')

P: 
 [[[0. 1. 1.]
  [0. 0. 1.]
  [0. 0. 0.]]

 [[0. 1. 1.]
  [0. 0. 1.]
  [0. 0. 0.]]

 [[0. 1. 1.]
  [0. 0. 1.]
  [0. 0. 0.]]]


# 2.2 Impartial culture

In [5]:
class Impartial_culture(Сulture):
    def setParams(self):
        self.ctype = "Impartial_culture"
    
    def createProfiles(self):
        
        tempP = np.zeros((self.n, self.K, self.K))
        for p in range(self.n):
            profile = list(range(self.K))
            random.shuffle(profile)
            for k1 in range(self.K):
                pos1 = profile[k1]
                for k2 in range(k1+1, self.K):
                    pos2 = profile[k2]
                    tempP[p, pos1, pos2] = 1
        self.P = tempP
        return tempP   

        

In [6]:
i = Impartial_culture(5,6)
i.setParams()
P= i.createProfiles()
print(f'P: \n {P}')

P: 
 [[[0. 1. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 0.]
  [1. 1. 0. 0. 1. 0.]
  [1. 1. 1. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 0.]]

 [[0. 1. 1. 1. 0. 1.]
  [0. 0. 1. 1. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 0. 1.]
  [0. 1. 1. 1. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 1. 0.]
  [1. 1. 0. 1. 1. 1.]
  [1. 1. 0. 0. 1. 1.]
  [1. 0. 0. 0. 0. 0.]
  [1. 1. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0. 1.]
  [1. 0. 1. 1. 1. 1.]
  [1. 0. 0. 1. 1. 1.]
  [0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 1. 1.]
  [0. 0. 0. 0. 1. 1.]
  [1. 1. 0. 1. 1. 1.]
  [1. 1. 0. 0. 1. 1.]
  [0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0.]]]


# 2.3 Distributive cultures

Everything is fine except for simple Gini

In [7]:
class Distributive_culture(Сulture):
    def setParams(self):
        self.ctype = "Distributive_culture"
    
#     def sharesIntoLinear(self, shares):
#         # [0.61, 0.85, 0.42, 0.13]: [1, 0, 2, 3]: 1 > 0 > 2 > 3 
#         linear_pr = [i for (v, i) in sorted([(v, i) for (i, v) in enumerate(shares)], reverse=True)]
#         return linear_pr
    
    def GiniIndex(self, c_pr: np.array):
        # Done
        growing = sorted(c_pr)
        accumulated = np.cumsum(growing)
        S = 0
        for i in range(len(accumulated)):
            S += ((i+1)/len(accumulated) - accumulated[i])
        S *= 2/len(accumulated)
        return S
    
    def simpleGiniIndex(self, c_pr: np.array):
        # Problem
        n = len(c_pr)
        growing = sorted(c_pr)
        accumulated = [0] + list(np.cumsum(growing))
        S = 0
        for i in range(1,n+1):
            S += ( (i-0.5) / n - (accumulated[i]+accumulated[i-1]) / 2)
        S *= 2/n
        return S
        
    def standartDeviation(self, c_pr: np.array):
        # Done
        return np.std(c_pr)

# 2.3.1 Consensual redistributive culture

Done

In [8]:
# Consensual redistributive culture
class Consensual_redistributive_culture(Distributive_culture):
    def setParams(self):
        self.ctype = "Distributive_culture"
        self.cctype = "Consensual_redistributive_culture"
        
        
    def createSharesProfiles(self):
        Y = []
        for i in range(self.n):
            Y.append(np.random.random((self.K)))
        X = []
        for i in range(self.n):
            X.append([])
            for j in range(self.K):
                X[-1].append(Y[i][j]/sum([Y[t][j] for t in range(self.n)]))
        return X
        
    def createProfiles(self):
        self.SharesProfiles = self.createSharesProfiles()
#         print(f'X : {np.matrix(X)}')
        tempP = np.zeros((self.n, self.K, self.K))
        for p in range(self.n):
            for k1 in range(self.K):
                for k2 in range(k1+1, self.K):
                    if(self.SharesProfiles[p][k1] >= self.SharesProfiles[p][k2]):
                        tempP[p, k1, k2] = 1
                    else:
                        tempP[p, k2, k1] = 1
        self.P = tempP
        return tempP   

In [9]:
crc = Consensual_redistributive_culture(n = 4, K = 6)
crc.setParams()
P= crc.createProfiles()
print(f'P: \n {P}')

P: 
 [[[0. 0. 1. 0. 1. 0.]
  [1. 0. 1. 0. 1. 1.]
  [0. 0. 0. 0. 1. 0.]
  [1. 1. 1. 0. 1. 1.]
  [0. 0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 0. 1.]
  [1. 0. 0. 0. 0. 1.]
  [1. 1. 1. 0. 0. 1.]
  [1. 1. 1. 1. 0. 1.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 1. 1. 1. 1. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 1. 0. 0.]
  [1. 1. 1. 1. 1. 0.]]

 [[0. 0. 0. 0. 1. 1.]
  [1. 0. 0. 1. 1. 1.]
  [1. 1. 0. 1. 1. 1.]
  [1. 0. 0. 0. 1. 1.]
  [0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0.]]]


## Something strange happend with SimpleGini. We didn't obtained exactly the same results.
Problems with simpleGini. SD and normal Gini work just fine.

In [10]:
def SimulateTable1(times = 100):
#     vals = [3,5,11,49,99,999]
    vals = [3,5,11,49,99]
    gini_avgs = ['Gini index']
    simple_gini_avgs = ['Simple Gini index']
    standart_deviations = ['Standart deviation']

    for n in vals:
        gini_avg = 0
        simple_gini_avg = 0
        standart_deviation = 0
        for t in range(times):
            crc = Consensual_redistributive_culture(n,1)
            crc.setParams()
            P = crc.createProfiles()
            shares = []
            for p in crc.SharesProfiles:
                shares.append(p[0])
            gini_avg += crc.GiniIndex(shares)
            simple_gini_avg += crc.simpleGiniIndex(shares)
            standart_deviation += crc.standartDeviation(shares)
        gini_avg /= times
        gini_avgs.append(gini_avg)
        simple_gini_avg /= times
        simple_gini_avgs.append(simple_gini_avg)
        standart_deviation /= times
        standart_deviations.append(standart_deviation)
    df = pd.DataFrame([standart_deviations, simple_gini_avgs, gini_avgs],columns=['n'] + vals)
    return df

df = SimulateTable1()
pd.set_option('display.max_columns', 50)  
pd.set_option('display.width', 1000)
pd.set_option('display.precision', 4)
print(f"\t\t\t \033[1m  Table 1  \033[0m")
print(df)


			   Table 1  
                    n       3       5      11      49      99
0  Standart deviation  0.1638  0.1040  0.0517  0.0116  0.0058
1   Simple Gini index  0.2519  0.2781  0.3180  0.3250  0.3301
2          Gini index  0.2519  0.2781  0.3180  0.3250  0.3301


# 2.3.2 Inegalitarian distributive cultures

In [11]:
# Inegalitarian distributive cultures
class Inegalitarian_distributive_culture(Distributive_culture):
    def setParams(self, e_min, e_max):
        self.ctype = "Distributive_culture"
        self.cctype = "Inegalitarian_distributive_culture"
        self.e_min = e_min
        self.e_max = e_max
        
        e = []
        for k in range(self.K):
            e.append(random.uniform(self.e_min, self.e_max))
    
    # ====================
    def createSharesProfiles(self):
        X = [[] for i in range(self.n)]
        e = []
        # define concentration parameter for each k:
        for k in range(self.K):
            e.append(random.uniform(self.e_min, self.e_max))
        for k in range(self.K):
            shares = self.defineShares(e[k])
            random.shuffle(shares)
            for i in range(self.n):
                X[i].append(shares[i])
        return X
        
    def createProfiles(self):
        self.SharesProfiles = self.createSharesProfiles()
        tempP = np.zeros((self.n, self.K, self.K))
        for p in range(self.n):
            for k1 in range(self.K):
                for k2 in range(k1+1, self.K):
                    if(self.SharesProfiles[p][k1] >= self.SharesProfiles[p][k2]):
                        tempP[p, k1, k2] = 1
                    else:
                        tempP[p, k2, k1] = 1
        self.P = tempP
        return tempP   

        
    def defineShares(self, e):
        v = [0] + [ ( (i+1) / self.n ) ** e  for i in range(self.n)]
        u = [v[i+1]-v[i] for i in range(self.n)]
        return u

In [12]:
crc = Inegalitarian_distributive_culture(4,6)
e_min = 2
e_max = 4

crc.setParams(e_min, e_max)
P= crc.createProfiles()
np.set_printoptions(precision=3)
print(f'SharesProfiles: {np.matrix(crc.SharesProfiles)}')
print(f'P: \n {P}')



SharesProfiles: [[0.04  0.009 0.179 0.039 0.007 0.553]
 [0.16  0.086 0.454 0.49  0.648 0.123]
 [0.313 0.282 0.313 0.313 0.074 0.021]
 [0.488 0.623 0.054 0.158 0.271 0.303]]
P: 
 [[[0. 1. 0. 1. 1. 0.]
  [0. 0. 0. 0. 1. 0.]
  [1. 1. 0. 1. 1. 0.]
  [0. 1. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 0.]]

 [[0. 1. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0.]
  [1. 1. 0. 0. 0. 1.]
  [1. 1. 1. 0. 0. 1.]
  [1. 1. 1. 1. 0. 1.]
  [0. 1. 0. 0. 0. 0.]]

 [[0. 1. 0. 1. 1. 1.]
  [0. 0. 0. 0. 1. 1.]
  [1. 1. 0. 1. 1. 1.]
  [0. 1. 0. 0. 1. 1.]
  [0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 1. 1. 1.]
  [1. 0. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 0. 1. 1. 0. 0.]
  [0. 0. 1. 1. 1. 0.]]]


# 2.4 Spatial cultures
not done

In [13]:
class Spatial_culture(Сulture):
    def setDimention(self, d):
        self.d = d
        self.ctype = "Spatial_culture"
        
    def utility(self, w, x):
        return - np.linalg.norm(x - w, ord=2)
        
    def createProfiles():
        pass
    
    

In [14]:
def generateCultureFile(culture: Сulture):
    if culture.ctype == "Rousseauist_culture":
        pass
    elif culture.ctype == "Impartial_culture":
        pass
    elif culture.ctype == "Distributive_culture":
        pass
    elif culture.ctype == "Spatial_culture":
        pass

# 3 Voting rules and behavior

In [15]:
class Voting:
    def __init__(self, culture):
        self.n = culture.n
        self.K = culture.K
        self.vtype = None
        self.culture = culture
        self.setParams()

# 3.1 Sincere voting

In [30]:
class SincereVoting(Voting):
    def setParams(self):
        self.vtype = 'SincereVoting'
        self.P = self.culture.P
        
    def Plurality(self):
        PluralityScore = np.zeros(self.K)
        for p in range(self.n):
            tempPS = np.zeros(self.K)
            scores = np.sum(self.P[p], axis = 0)
            tempBests = np.argwhere(scores == np.amax(scores))
            for best in tempBests:
                tempPS[best] += 1/len(tempBests)
            PluralityScore += tempPS
        return PluralityScore
        
    def createBordaMatrix(self):
        bordaMatrix = np.zeros((self.K, self.K))
        for p in range(self.n):
            bordaMatrix += self.P[p]
        for k in range(self.K):
            bordaMatrix[k,k] = self.n/2
        return bordaMatrix
    
    def BordaScores(self):
        self.bordaMatrix = self.createBordaMatrix()
        bs = []
        for k1 in range(self.K):
            bs.append(0)
            for k2 in range(self.K):
                bs[k1] += self.bordaMatrix[k1][k2]
        return bs
    
    def BordaWinner(self):
        bs = self.BordaScores()
        winner = np.argmax(bs)
        return winner

    def CopelandScores(self):
        self.bordaMatrix = self.createBordaMatrix()
        self.tournamentMatrix = [[int(el > self.n/2) for el in line] for line in self.bordaMatrix]
        cs = []
        for k1 in range(self.K):
            cs.append(0)
            for k2 in range(self.K):
                cs[k1] += self.tournamentMatrix[k1][k2]
        return cs
    
    def CopelandWinner(self):
        cs = self.CopelandScores()
        winner = np.argmax(cs)
        return winner
    
    def checkCondorsetWinner(self):
        cs = self.CopelandScores()
        if(self.K-1 in cs):
            return True, np.argmax(cs)
        return False, -1

In [31]:
# r = Rousseauist_culture(4,10)
r = Rousseauist_culture(3,5)
r.setParams(0,0.2)
P = r.createProfiles()
print(f'P: \n {P}')

# If there are fractions in answer, then preferences aren't strict.
SV = SincereVoting(r)
print(f'Plurality Score: {SV.Plurality()}')
print(f'Borda Score: {SV.BordaScores()}')
print(f'Copeland Score: {SV.CopelandScores()}')
print(f'CondorsetWinner: {SV.checkCondorsetWinner()}')

P: 
 [[[0. 0. 1. 1. 1.]
  [1. 0. 0. 1. 1.]
  [0. 1. 0. 0. 1.]
  [0. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0.]]

 [[0. 1. 1. 0. 0.]
  [0. 0. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 1.]
  [1. 0. 1. 0. 0.]]

 [[0. 0. 1. 1. 0.]
  [1. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0.]
  [0. 1. 1. 0. 1.]
  [1. 0. 1. 0. 0.]]]
Plurality Score: [0. 0. 2. 0. 1.]
Borda Score: [8.5, 9.5, 4.5, 9.5, 5.5]
Copeland Score: [2, 3, 1, 2, 2]
CondorsetWinner: (False, -1)


# 3.2 Responsive voting

In [32]:
class ResponsiveVoting(Voting):
    def setParams(self):
        self.vtype = 'ResponsiveVoting'
        self.P = self.culture.P
        
    def Plurality(self):
        # We always assume that announced scores is 0 > 1 > 2 > ... > K-1
        PluralityScore = np.zeros(self.K)
        for p in range(self.n):
            tempPS = np.zeros(self.K)
            scores = np.sum(self.P[p], axis = 0)
            tempBests = np.argwhere(scores == np.amax(scores))
            for best in tempBests:
                tempPS[best] += 1/len(tempBests)
            PluralityScore += tempPS
        
        
        return PluralityScore
        
    def createBordaMatrix(self):
        bordaMatrix = np.zeros((self.K, self.K))
        for p in range(self.n):
            bordaMatrix += self.P[p]
        for k in range(self.K):
            bordaMatrix[k,k] = self.n/2
        return bordaMatrix
    
    def BordaScores(self):
        #Starting with Borda ranking
        self.bordaMatrix = self.createBordaMatrix()
        bs = []
        for k1 in range(self.K):
            bs.append(0)
            for k2 in range(self.K):
                bs[k1] += self.bordaMatrix[k1][k2]
        return bs
    
    def BordaWinner(self):
        bs = self.BordaScores()
        winner = np.argmax(bs)
        return winner

    def CopelandScores(self):
        self.bordaMatrix = self.createBordaMatrix()
        self.tournamentMatrix = [[int(el > self.n/2) for el in line] for line in self.bordaMatrix]
        cs = []
        for k1 in range(self.K):
            cs.append(0)
            for k2 in range(self.K):
                cs[k1] += self.tournamentMatrix[k1][k2]
        return cs
    
    def CopelandWinner(self):
        cs = self.CopelandScores()
        winner = np.argmax(cs)
        return winner
    
    def checkCondorsetWinner(self):
        cs = self.CopelandScores()
        if(self.K-1 in cs):
            return True, np.argmax(cs)
        return False, -1
    
    def ApprovalVoting(self):
        #Starting with Copeland ranking
        cs = self.CopelandScores()
        

# 4 Results

# 4.1 Results for Rousseauist cultures

### Tables 3 and 4 simulations:
Results are little too good. Maybe we have to check that getP is right

In [33]:
def SimulateTable34(n, K, alpha, beta, simulation_runs):
    CondorChance = 0
    CondorRousseauChance = 0
    for i in range(simulation_runs):
        r = Rousseauist_culture(n,K)
        r.setParams(alpha, beta)
        P = r.createProfiles()
        v = SincereVoting(r)
        CW_exists, CW_num = v.checkCondorsetWinner()
        if(CW_exists):
            CondorChance += 1
            # We assume that truee order is 0 > 1 > 2 > ... > K -1
            # So Rousseau winner is 0
            CondorRousseauChance += int(CW_num == 0)
    # print(f'Probability for the Condorset winner  {CondorChance/simulation_runs}')
    return CondorChance/simulation_runs, CondorRousseauChance/simulation_runs

In [34]:
simulation_runs = 1000

n = 5
K_values = [5, 11]
alpha_values = [0, 0.4, 0.7, 1]
beta_values  = [0, 0.3, 0.5, 0.7, 1]

for K in K_values:
    print(f"\t\t\t \033[1m  n = {n} K = {K}  \033[0m")
    # print('')
    df = pd.DataFrame(columns=['beta = '+str(beta) for beta in beta_values])
    for alpha in alpha_values:
        line = []
        for beta in beta_values:
            CondorChance, CondorRousseauChance  = SimulateTable34(n, K, alpha, beta, simulation_runs)
            line.append(str(CondorChance) + ' (' +str(CondorRousseauChance) +')' )
        df.loc[f'alpha = {alpha}'] = line
    print(df)
    print('\n')


			   n = 5 K = 5  
                  beta = 0     beta = 0.3     beta = 0.5     beta = 0.7       beta = 1
alpha = 0    0.302 (0.052)  0.384 (0.191)  0.536 (0.308)  0.592 (0.382)  0.664 (0.439)
alpha = 0.4  0.394 (0.228)   0.629 (0.42)   0.74 (0.511)  0.808 (0.572)  0.848 (0.618)
alpha = 0.7  0.536 (0.399)  0.765 (0.586)  0.848 (0.702)  0.911 (0.742)  0.925 (0.749)
alpha = 1    0.699 (0.593)  0.868 (0.756)  0.933 (0.819)  0.956 (0.839)  0.972 (0.842)


			   n = 5 K = 11  
                  beta = 0     beta = 0.3     beta = 0.5     beta = 0.7       beta = 1
alpha = 0      0.012 (0.0)  0.307 (0.157)   0.48 (0.281)   0.608 (0.39)   0.67 (0.431)
alpha = 0.4  0.034 (0.014)  0.563 (0.403)  0.726 (0.535)  0.789 (0.577)   0.86 (0.636)
alpha = 0.7  0.136 (0.094)  0.744 (0.609)   0.841 (0.68)  0.903 (0.747)  0.921 (0.732)
alpha = 1    0.272 (0.235)  0.852 (0.751)  0.931 (0.828)   0.95 (0.856)  0.968 (0.855)




In [21]:
def SimulateTable56(n, K, alpha, beta, simulation_runs):
    CondorNum = 0
    CondorRousseauNum = 0
    CopelandRes = 0
    AV = []
    BordaRes = [0,[]]
    for i in range(simulation_runs):
        r = Rousseauist_culture(n,K)
        r.setParams(alpha, beta)
        matrix = r.createMatrices()
        v = Voting(r, matrix)
        if(v.checkCondorsetWinner()):
            CondorNum += 1
            # We assume that truee order is 0 > 1 > 2 > ... > K -1
            # So Rousseau winner is 0
            CondorRousseauNum += int(v.CopelandWinner() == 0)
            CopelandRes += 1 + v.CopelandWinner()
            BordaRes[0] += 1 + v.BordaWinner()
    CopelandRes = CopelandRes /simulation_runs
    BordaRes[0] = BordaRes[0] /simulation_runs

    return CondorNum/simulation_runs, CondorRousseauNum/simulation_runs, CopelandRes, AV, BordaRes

In [22]:
# Table 5
simulation_runs = 3000

n_values = [5,11]
K = 5
alpha = 0.4
beta  = 0.5
print(f"\t\t\t \033[1m  alpha =.4, beta=.5, K=5  \033[0m")
df = pd.DataFrame(columns=['n = 5', 'n = 11'])
# df = pd.DataFrame(columns=['\033[1m alpha =.4, beta=.5, K=5 \033[0m', 'n = 5', 'n = 11'])
cols = {}
for n in n_values:
    cols[f'n = {n}']={}
    CondorCh, CondorRousseauCh, CopelandR, AV, BordaRes  = SimulateTable56(n, K, alpha, beta, simulation_runs)
    cols[f'n = {n}']['Pr. of Condorcet :'] = CondorCh
    cols[f'n = {n}']['Pr. of Rousseau-Condorcet :'] = CondorRousseauCh
    cols[f'n = {n}']['Rule'] = 'Average rank'
    cols[f'n = {n}']['Copeland'] = CopelandRes
    for i in range(len(AV)):
        cols[f'n = {n}'][f'AV{i+1}'] = AV[i]
    cols[f'n = {n}']['Borda'] = BordaRes[0]
    for i in range(len(CopelandRes[1])):
        cols[f'n = {n}'][f'Borda{i+1}'] = BordaRes[1][i]
    for key in cols[f'n = {n}'].keys():
        df.at[key,f'n = {n}'] = cols[f'n = {n}'][key]
pd.set_option('display.max_columns', 50)  
pd.set_option('display.width', 1000)
pd.set_option('display.precision', 4)
print(df)


			   alpha =.4, beta=.5, K=5  


AttributeError: 'Rousseauist_culture' object has no attribute 'createMatrices'

In [ ]:
class Voting_old:
    def __init__(self, filepath, method):
        self.df = pd.read_csv(filepath)
        self.df = self.df.drop('Same', axis=1)
        self.alternatives = set(self.df.columns)
        self.method = method

        # All preferences for each alternative
        self.ALTR_dict = {} # was profile_dict
        for cand in self.alternatives:
            self.ALTR_dict[cand] = self.df[cand].values

        # Preferences for each voter
        self.INDV_d = {}
        for itr, row in self.df.iterrows():
            self.INDV_d[itr]=row.to_dict()

    def voting(self):
        if (self.method == 'Plurality'):
            return self.plurality_voting()
        elif (self.method == 'Borda'):
            return self.borda_voting()
        elif (self.method == 'Nanson'):
            return self.nanson_voting()
        elif (self.method == 'STV'):
            return self.stv_voting()
        elif (self.method == 'Copeland'):
            return self.copeland_voting()
        elif (self.method == 'OurMethod'):
            return self.our_voting()


    # Common fuctions:
    def reboot(self):
        # Normalize
        self.df = self.normalize_df(self.df)
        self.alternatives = set(self.df.columns)

        self.ALTR_dict = {}
        for cand in self.alternatives:
            self.ALTR_dict[cand] = self.df[cand].values

        # Preferences for each voter
        self.INDV_d = {}
        for itr, row in self.df.iterrows():
            self.INDV_d[itr]=row.to_dict()

        return self.df

    def normalize_df(self, df):
        new_df = pd.DataFrame(columns=df.columns)
        for itr, row in df.iterrows():
            new_row = {}
            sorted_dict = sorted(row.to_dict().items(), key=operator.itemgetter(1))
            for i, el in enumerate(sorted_dict):
                new_row[el[0]] = i + 1
            new_df = new_df.append(new_row, ignore_index=True)
        return new_df

    def lexicografic_order(self, winners):
        winners.sort()
        return winners[0]

    def get_winners(self, score_dict):
        winners = []
        max_val = max([i for i in score_dict.values()])
        for key in score_dict.keys():
            if(score_dict[key]==max_val):
                winners.append(key)
        return winners

    def get_losers(self, score_dict):
        losers = []
        if(self.method == 'Nanson'):
            Mean = np.mean([score_dict[cand] for cand in score_dict.keys()])
            for cand in self.alternatives:
                if(score_dict[cand]<Mean):
                    self.df = self.df.drop(cand, axis=1)
        elif(self.method == 'STV'):
            min_val = min([i for i in score_dict.values()])
            for key in score_dict.keys():
                if(score_dict[key]==min_val):
                    losers.append(key)
        elif (self.method == 'OurMethod'):
            max_val = max([i for i in score_dict.values()])
            for key in score_dict.keys():
                if (score_dict[key] == max_val):
                    losers.append(key)
        return losers

    def checkCondorset(self, show=False):
        for el1 in self.alternatives:
            Winner_Flag = True
            for el2 in self.alternatives:
                if(el1!=el2):
                    scores = [0, 0]
                    for itr, row in self.df.iterrows():
                        if(self.df[el1][itr]<self.df[el2][itr]):
                            # el1 - winner
                            scores[0] += 1
                        else:
                            scores[1] += 1
                    if(scores[0]>scores[1]):
                        pass
                    elif (scores[0] < scores[1]):
                        condorset_winner = None
                        Winner_Flag = False
                        break
            if(Winner_Flag):
                if(show):
                    print(f'Alternative {el1} is a Condorcet winner.')
                self.df = self.df.drop(el1, axis=1)
                self.df = self.reboot()
                return True
        return False

    def deleteCondorset(self, show=False):

        Cond_Win = self.checkCondorset(show)
        while (Cond_Win):
            Cond_Win = self.checkCondorset(show)

    # Plurality:
    def plurality_score(self, cand):
        return sum([el == 1 for el in self.ALTR_dict[cand]])

    def plurality_voting(self):
        score_dict = {}
        for cand in self.alternatives:
            score_dict[cand] = self.plurality_score(cand)
        winners = self.get_winners(score_dict)
        return self.lexicografic_order(winners), score_dict

    # Borda:
    def pref_into_borda(self, alternative_prefs, m):
        res_list = []
        for pref in alternative_prefs:
            res_list.append(m-pref)
        return res_list

    def borda_score(self, cand, m):
        return sum(self.pref_into_borda(self.ALTR_dict[cand], m))

    def borda_voting(self):
        score_dict = {}
        m = len(self.alternatives)
        for cand in self.alternatives:
            score_dict[cand] = self.borda_score(cand, m)
        winners = self.get_winners(score_dict)
        return self.lexicografic_order(winners), score_dict

    # Nanson
    def nanson_voting(self):

        score_dict = {}
        m = len(self.alternatives)

        for cand in self.alternatives:
            score_dict[cand] = self.borda_score(cand, m)

        winners = self.get_winners(score_dict)
        while(len(winners)!=len(self.alternatives)):
            losers = self.get_losers(score_dict)
            for loser in losers:
                self.df = self.df.drop(loser, axis=1)

            self.df = self.reboot()
            m = len(self.alternatives)

            score_dict = {}
            for cand in self.alternatives:
                score_dict[cand] = self.borda_score(cand, m)

            winners = self.get_winners(score_dict)

        winners = self.get_winners(score_dict)
        return self.lexicografic_order(winners), score_dict

    # STV
    def stv_score(self, cand):
        return sum([el == 1 for el in self.ALTR_dict[cand]])

    def stv_voting(self):
        # Get scores
        score_dict = {}
        for cand in self.alternatives:
            score_dict[cand] = self.stv_score(cand)
        # Check two or more winners
        winners = self.get_winners(score_dict)
        while(len(winners)!=len(self.alternatives)):
            losers = self.get_losers(score_dict)
            for loser in losers:
                self.df = self.df.drop(loser, axis=1)
            # Normalize
            self.df = self.reboot()

            score_dict = {}
            for cand in self.alternatives:
                score_dict[cand] = self.stv_score(cand)

            winners = self.get_winners(score_dict)

        winners = self.get_winners(score_dict)
        return self.lexicografic_order(winners), score_dict

    # Copeland
    def build_dominance_graph(self):
        graph = {}
        reverse_graph = {}
        for cand in self.alternatives:
            graph[cand] = set()
            reverse_graph[cand] = set()

        for el1 in self.alternatives:
            for el2 in self.alternatives:
                if (el1 != el2):
                    scores = [0, 0]
                    for itr, row in self.df.iterrows():
                        if (self.df[el1][itr] < self.df[el2][itr]):
                            # el1 - winner
                            scores[0] += 1
                        else:
                            scores[1] += 1
                    if (scores[0] > scores[1]):
                        graph[el1].add(el2)
                        reverse_graph[el2].add(el1)
                    elif (scores[0] < scores[1]):
                        graph[el2].add(el1)
                        reverse_graph[el1].add(el2)

        return graph, reverse_graph

    def copeland_score(self, cand):
        return len(self.graph[cand])

    def copeland_voting(self):
        self.graph, self.reversed_graph = self.build_dominance_graph()
        score_dict = {}
        for cand in self.alternatives:
            score_dict[cand] = self.copeland_score(cand)
        winners = self.get_winners(score_dict)
        return self.lexicografic_order(winners), score_dict

